#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "elabftw"
name = "eLabFTW"
description.en = "Open source electronic lab notebook for research labs"
description.fr = "Cahier de laboratoire électronique open source pour les laboratoires de recherche"

version = "5.0.4~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://www.elabftw.net"
demo = "https://demo.elabftw.net/login.php"
admindoc = "https://doc.elabftw.net/"
code = "https://github.com/elabftw/elabftw"
cpe = "cpe:2.3:a:elabftw:elabftw"
fund = "https://github.com/sponsors/NicolasCARPi"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "4000M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, eLabFTW will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, eLabFTW sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/elabftw/elabftw/archive/refs/tags/5.0.4.tar.gz"
    sha256 = "8591aec1dee7310d0e98a10bf6f6d59c57f8749f10c16bd4c1219bbafd5639a7"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "brotli",
        "zopfli",
        "php-bcmath",
        "php8.2-curl",
        "php8.2-ctype",
        "php8.2-dev",
        "php8.2-dom",
        "php8.2-exif",
        "php8.2-gd",
        "php8.2-gettext",
        "php8.2-fileinfo",
        "php8.2-fpm",
        "php8.2-json",
        "php8.2-intl",
        "php8.2-ldap",
        "php8.2-mbstring",
        "php8.2-opcache",
        "php8.2-mysql",
        "php8.2-imagick",
        "php8.2-phar",
        "php8.2-redis",
        "php8.2-simplexml",
        "php8.2-tokenizer",
        "php8.2-xml",
        "php8.2-xmlwriter",
        "php8.2-zip",
    ]


    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]

    [resources.database]
    type = "mysql"
