#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "elabftw"
name = "eLabFTW"
description.en = "Open source electronic lab notebook for research labs"
description.fr = "Cahier de laboratoire électronique open source pour les laboratoires de recherche"

version = "5.1.14~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://www.elabftw.net"
demo = "https://demo.elabftw.net/login.php"
admindoc = "https://doc.elabftw.net/"
code = "https://github.com/elabftw/elabftw"
cpe = "cpe:2.3:a:elabftw:elabftw"
fund = "https://github.com/sponsors/NicolasCARPi"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64","arm64"]
multi_instance = true

ldap = true

sso = false

disk = "1000M"
ram.build = "400M"
ram.runtime = "300M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, eLabFTW will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, eLabFTW sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.docker]
    format = "docker"
    extract = true
    prefetch = false
    amd64.url = "elabftw/elabimg:5.1.14"
    amd64.sha256 = "a8123a8bef306a7259409f79a0c57b23d6feafe82c1d690af1579da5791a489d"
    arm64.url = "elabftw/elabimg:5.1.14"
    arm64.sha256 = "1b3b185cb2c35f66407f374813333492de4b141ce27d15bc3f2b08f33e542af7"
    autoupdate.upstream = "https://github.com/elabftw/elabftw/"
    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "bash",
        "brotli",
        "curl",
        "ghostscript",
        "git",
        "nodejs",
        "openssl",
        "php8.3",
        "php8.3-bcmath",
        "php8.3-curl",
        "php8.3-ctype",
        "php8.3-dev",
        "php8.3-dom",
        "php8.3-exif",
        "php8.3-gd",
        "php8.3-gettext",
        "php8.3-fileinfo",
        "php8.3-fpm",
        "php8.3-iconv",
        "php8.3-intl",
        "php8.3-json",
        "php8.3-ldap",
        "php8.3-mbstring",
        "php8.3-mysql",
        "php8.3-imagick",
        "php8.3-opcache",
        "php8.3-phar",
        "php8.3-redis",
        "php8.3-simplexml",
        "php8.3-tokenizer",
        "php8.3-xml",
        "php8.3-xmlwriter",
        "php8.3-zip",
        "tzdata",
        "unzip",
        "zopfli",
        "mariadb-server",
    ]

    [resources.database]
    type = "mysql"
