#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "elabftw"
name = "eLabFTW"
description.en = "Open source electronic lab notebook for research labs"
description.fr = "Cahier de laboratoire électronique open source pour les laboratoires de recherche"

version = "5.1.14~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://www.elabftw.net"
demo = "https://demo.elabftw.net/login.php"
admindoc = "https://doc.elabftw.net/"
code = "https://github.com/elabftw/elabftw"
cpe = "cpe:2.3:a:elabftw:elabftw"
fund = "https://github.com/sponsors/NicolasCARPi"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "4000M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    help.en = "If enabled, eLabFTW will be accessible by people who do not have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, eLabFTW sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/elabftw/elabftw/archive/refs/tags/5.1.14.tar.gz"
    sha256 = "9e7e73e901f2ef90f3cbb9b6b16e0d5d9360a2843a59e810861465b8cd531fa8"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "brotli",
        "zopfli",
        "php-bcmath",
        "php8.0-curl",
        "php8.0-ctype",
        "php8.0-dev",
        "php8.0-dom",
        "php8.0-exif",
        "php8.0-gd",
        "php8.0-gettext",
        "php8.0-fileinfo",
        "php8.0-fpm",
        "php8.0-json",
        "php8.0-intl",
        "php8.0-ldap",
        "php8.0-mbstring",
        "php8.0-opcache",
        "php8.0-mysql",
        "php8.0-imagick",
        "php8.0-phar",
        "php8.0-redis",
        "php8.0-simplexml",
        "php8.0-tokenizer",
        "php8.0-xml",
        "php8.0-xmlwriter",
        "php8.0-zip",
        "mariadb-server",
    ]


    [resources.apt.extras.yarn]
    repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    packages = ["yarn"]

    [resources.database]
    type = "mysql"
