#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================


source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=7

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir/docker/" --source_id="docker"

mkdir -p "$install_dir/live/"
rsync -a "$install_dir/docker/elabftw/" "$install_dir/live/"
ynh_secure_remove --file="$install_dir/docker"

mkdir -p "$install_dir/live/"{cache,uploads}

# Fix Unknown collation: 'utf8mb4_0900_ai_ci'
for f in $install_dir/live/src/sql/*.sql ; do
    ynh_replace_string --match_string="utf8mb4_0900_ai_ci" --replace_string="utf8mb4_general_ci" --target_file="$f"
done

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression --message="Adding $app's configuration files..." --weight=30

pushd "$install_dir/live"
    secret_key=$(php$phpversion $install_dir/live/bin/install genkey)
    ynh_app_setting_set --app=$app --key="secret_key" --value="$secret_key"

    ynh_add_config --template="config.php" --destination="$install_dir/live/config.php"
    ynh_exec_as "$app" "php$phpversion" "bin/install" start -q
popd

ynh_script_progression --message="Configuring LDAP and emails..." --weight=2
ynh_add_config --template="sql.template" --destination="$install_dir/ldap_sql"
ynh_mysql_connect_as --user="$db_user" --password="$db_pwd" --database="$db_name" < "$install_dir/ldap_sql"
ynh_secure_remove --file="$install_dir/ldap_sql"

# Create a cron file
ynh_add_config --template="cron" --destination="/etc/cron.d/$app"

chmod -R o-rwx "$install_dir"
chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated PHP-FPM config
ynh_add_fpm_config

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
